### ISSUE TITLE
Output piping pause

### ISSUE THREAD

**Issue by edmundjc** [RogueAI42/merac-o-matic#1]
When piping the output of merac-o-matic to another application (like Festival) while executing from a terminal shell in X, the output pauses part way through until the dialog created by the shell script is acknowledged by the user.

**Comment by RogueAI42** [comment]
Yeah. I saw your fix. I've been working on a better interface using Python and GTKBuilder, which would integrate with Festival, but it's not going well. When I get home I'll upload what I've done so far, maybe you can help.

**Comment by RogueAI42** [comment]
The GUI now integrates with Festival as of f078d31!
