### ISSUE TITLE
VB Script Port

### ISSUE THREAD

**Issue by edmundjc** [RogueAI42/merac-o-matic#3]
As an act of good faith, it may be good to develop a VB Script version of Merac-O-Matic alongside the main one.  Windows may be on the decline, but it's unfair to prevent other good folk from running this fine program simply because they fail to meet the minimum requirement of *anything that runs bash*.

**Comment by RogueAI42** [comment]
Wouldn't it make more sense to make a cygwin wrapper?

**Comment by edmundjc** [comment]
*^with tongue planted firmly in cheek^* Perhaps, but it would be a shame if we gave Linux users reason to troll Windows users because the recommended hardware for the Windows version is much higher than it is for the Linux version.  Or that Merac-O-Matic for Windows runs at a lower framerate.

**Comment by RogueAI42** [comment]
I swear, you're a delusional Linux hating hipster. :P

**Comment by RogueAI42** [comment]
Merac-O-Matic: The Next Generation, being a Python program, should run perfectly fine on Windows as long as the end user has Python. So when it comes time to make a port, we can just bundle a Python runtime with the Merac-O-Matic installer and have it run as perfectly as Windows can. I won't close this issue until we make said port though.

**Comment by RogueAI42** [comment]
I've succeeded! There's a script, sorry, "batch file", which can generate a Merac-O-Matic package, sorry, "installer", as long as you have Python 3 (yuck), PyInstaller, and Inno Setup on your PATH.
